"""Module de dépôts"""

from .depot_postgres import DepotPostgres
from .depot_domaine_valeur_postgres import DepotDomaineValeurPostgres
from .depot_entreprise_postgres import DepotEntreprisePostgres
from .depot_nom_postgres import DepotNomPostgres
from .depot_etablissement_postgres import DepotEtablissementPostgres
from .depot_fusion_scission_postgres import DepotFusionScissionPostgres
from .depot_continuation_transformation_postgres import DepotContinuationTransformationPostgres
from .unite_travail_postgres import UniteTravailPostgres
