"""Dépôt d'entreprises postgres"""

from psycopg2.errors import Error

from .depot_postgres import DepotPostgres
from ..entreprise import Entreprise

UPSERT_ENTREPRISE = """
    insert into donnees_ouvertes.entreprise(
        neq,
        ind_fail,
        dat_immat,
        cod_regim_juri,
        cod_intval_emplo_que,
        dat_cess_prevu,
        cod_stat_immat,
        cod_forme_juri,
        dat_stat_immat,
        cod_regim_juri_consti,
        dat_depo_declr,
        an_decl,
        an_prod,
        dat_limit_prod,
        an_prod_pre,
        dat_limit_prod_pre,
        dat_maj_index_nom,
        cod_act_econ_cae,
        no_act_econ_assuj,
        desc_act_econ_assuj,
        cod_act_econ_cae2,
        no_act_econ_assuj2,
        desc_act_econ_assuj2,
        nom_loclt_consti,
        dat_consti,
        ind_conven_unmn_actnr,
        ind_ret_tout_pouvr,
        ind_limit_resp,
        dat_deb_resp,
        dat_fin_resp,
        objet_soc,
        no_mtr_volont,
        adr_domcl_adr_disp,
        adr_domcl_lign1_adr,
        adr_domcl_lign2_adr,
        adr_domcl_lign3_adr,
        adr_domcl_lign4_adr
    ) values (
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s,
        %s
    ) on conflict (
        neq
    ) do update set
        ind_fail = excluded.ind_fail,
        dat_immat = excluded.dat_immat,
        cod_regim_juri = excluded.cod_regim_juri,
        cod_intval_emplo_que = excluded.cod_intval_emplo_que,
        dat_cess_prevu = excluded.dat_cess_prevu,
        cod_stat_immat = excluded.cod_stat_immat,
        cod_forme_juri = excluded.cod_forme_juri,
        dat_stat_immat = excluded.dat_stat_immat,
        cod_regim_juri_consti = excluded.cod_regim_juri_consti,
        dat_depo_declr = excluded.dat_depo_declr,
        an_decl = excluded.an_decl,
        an_prod = excluded.an_prod,
        dat_limit_prod = excluded.dat_limit_prod,
        an_prod_pre = excluded.an_prod_pre,
        dat_limit_prod_pre = excluded.dat_limit_prod_pre,
        dat_maj_index_nom = excluded.dat_maj_index_nom,
        cod_act_econ_cae = excluded.cod_act_econ_cae,
        no_act_econ_assuj = excluded.no_act_econ_assuj,
        desc_act_econ_assuj = excluded.desc_act_econ_assuj,
        cod_act_econ_cae2 = excluded.cod_act_econ_cae2,
        no_act_econ_assuj2 = excluded.no_act_econ_assuj2,
        desc_act_econ_assuj2 = excluded.desc_act_econ_assuj2,
        nom_loclt_consti = excluded.nom_loclt_consti,
        dat_consti = excluded.dat_consti,
        ind_conven_unmn_actnr = excluded.ind_conven_unmn_actnr,
        ind_ret_tout_pouvr = excluded.ind_ret_tout_pouvr,
        ind_limit_resp = excluded.ind_limit_resp,
        dat_deb_resp = excluded.dat_deb_resp,
        dat_fin_resp = excluded.dat_fin_resp,
        objet_soc = excluded.objet_soc,
        no_mtr_volont = excluded.no_mtr_volont,
        adr_domcl_adr_disp = excluded.adr_domcl_adr_disp,
        adr_domcl_lign1_adr = excluded.adr_domcl_lign1_adr,
        adr_domcl_lign2_adr = excluded.adr_domcl_lign2_adr,
        adr_domcl_lign3_adr = excluded.adr_domcl_lign3_adr,
        adr_domcl_lign4_adr = excluded.adr_domcl_lign4_adr
"""

class DepotEntreprisePostgres(DepotPostgres):
    """Dépôt d'entreprises postgres"""

    def mettre_a_jour(self, item: Entreprise):
        try:
            self._curseur.execute(
                UPSERT_ENTREPRISE,
                (
                    item.neq,
                    item.ind_fail,
                    item.dat_immat,
                    item.cod_regim_juri,
                    item.cod_intval_emplo_que,
                    item.dat_cess_prevu,
                    item.cod_stat_immat,
                    item.cod_forme_juri,
                    item.dat_stat_immat,
                    item.cod_regim_juri_consti,
                    item.dat_depo_declr,
                    item.an_decl,
                    item.an_prod,
                    item.dat_limit_prod,
                    item.an_prod_pre,
                    item.dat_limit_prod_pre,
                    item.dat_maj_index_nom,
                    item.cod_act_econ_cae,
                    item.no_act_econ_assuj,
                    item.desc_act_econ_assuj,
                    item.cod_act_econ_cae2,
                    item.no_act_econ_assuj2,
                    item.desc_act_econ_assuj2,
                    item.nom_loclt_consti,
                    item.dat_consti,
                    item.ind_conven_unmn_actnr,
                    item.ind_ret_tout_pouvr,
                    item.ind_limit_resp,
                    item.dat_deb_resp,
                    item.dat_fin_resp,
                    item.objet_soc,
                    item.no_mtr_volont,
                    item.adr_domcl_adr_disp,
                    item.adr_domcl_lign1_adr,
                    item.adr_domcl_lign2_adr,
                    item.adr_domcl_lign3_adr,
                    item.adr_domcl_lign4_adr
                )
            )
        except Error as ex:
            print(f"Impossible d'insérer l'entreprise {item.neq}")
            raise ex
